# Generated by Django 5.2.17 on 2026-09-18 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("reply", "Reply"),
                            ("reaction", "Reaction"),
                            ("follow", "Follow"),
                            ("connection_request", "Connection request"),
                            ("connection_accepted", "Connection accepted"),
                            ("message", "Message"),
                            ("mention", "Mention"),
                            ("community", "Community"),
                            ("share", "Share"),
                            ("insight", "Insight"),
                            ("milestone", "Milestone"),
                            ("reminder", "Reminder"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("target_label", models.CharField(blank=True, max_length=200)),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("actor_count", models.PositiveIntegerField(default=1)),
                (
                    "dedupe_key",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who did the thing. Null for system notifications.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_caused",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-updated_at"],
                        name="notificatio_recipie_44bca6_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                ],
            },
        ),
    ]
