# Generated by Django 6.1.1 on 2026-09-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('entry_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('voice', 'Voice')], default='text', max_length=10)),
                ('mood', models.CharField(blank=True, choices=[('happy', 'Happy'), ('calm', 'Calm'), ('excited', 'Excited'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('angry', 'Angry'), ('tired', 'Tired'), ('overwhelmed', 'Overwhelmed')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('connections', 'Connections'), ('community', 'Community')], default='private', max_length=20)),
                ('prompt_used', models.CharField(blank=True, max_length=300)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='journal/media/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
