# Generated by Django 5.2.17 on 2026-09-18 15:04

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_journalcomment_journalcommentreaction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalmedia",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="journalentry",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="identity",
            field=models.CharField(
                choices=[
                    ("username", "Show my username"),
                    ("anonymous", "Post anonymously"),
                ],
                default="username",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="include_date",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="include_mood",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="journalmedia",
            name="caption",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="journalmedia",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="journalmedia",
            name="kind",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="journalmedia",
            name="file",
            field=models.FileField(upload_to=core.uploads.safe_upload_name),
        ),
    ]
