# Generated by Django 5.2.17 on 2026-09-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_alter_journalmedia_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalcomment",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
