# Generated by Django 5.2.17 on 2026-09-18 15:04

import core.uploads
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=80)),
                ("icon", models.CharField(blank=True, max_length=8)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "content categories",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "medium",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("article", "Article"),
                        ],
                        default="video",
                        max_length=10,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "media_file",
                    models.FileField(
                        blank=True, null=True, upload_to=core.uploads.safe_upload_name
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.uploads.safe_upload_name
                    ),
                ),
                ("thumbnail_emoji", models.CharField(blank=True, max_length=8)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="published",
                        max_length=10,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content",
                        to="content.contentcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="content.content",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="content.content",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentSave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="content.content",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_saves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="content.content",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress_seconds", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("first_viewed_at", models.DateTimeField(auto_now_add=True)),
                ("last_viewed_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="content.content",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["status", "-created_at"], name="content_con_status_867dbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["category", "-created_at"],
                name="content_con_categor_f081b3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="content",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("body", ""),
                    ("external_url", ""),
                    ("media_file", ""),
                    _negated=True,
                ),
                name="content_has_a_body_file_or_url",
            ),
        ),
        migrations.AddIndex(
            model_name="contentcomment",
            index=models.Index(
                fields=["content", "-created_at"], name="content_con_content_3dc72e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreaction",
            constraint=models.UniqueConstraint(
                fields=("content", "user"), name="unique_content_reaction"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsave",
            constraint=models.UniqueConstraint(
                fields=("content", "user"), name="unique_content_save"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentshare",
            constraint=models.UniqueConstraint(
                fields=("content", "user"), name="unique_content_share"
            ),
        ),
        migrations.AddIndex(
            model_name="contentview",
            index=models.Index(
                fields=["user", "-last_viewed_at"],
                name="content_con_user_id_3fd1c8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentview",
            constraint=models.UniqueConstraint(
                fields=("content", "user"), name="unique_content_view"
            ),
        ),
    ]
