# Generated by Django 5.2.17 on 2026-09-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sanctuary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
