# Generated by Django 5.2.17 on 2026-09-19 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("icon", models.CharField(blank=True, max_length=8)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("current_streak", "Current streak (days)"),
                            ("best_streak", "Longest streak ever (days)"),
                            ("entries", "Journal entries written"),
                            ("mood_checkins", "Mood check-ins logged"),
                            ("connections", "Accepted connections"),
                            ("posts", "Sanctuary posts shared"),
                            ("reactions_received", "Reactions received"),
                        ],
                        max_length=30,
                    ),
                ),
                ("threshold", models.PositiveIntegerField()),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "threshold"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_at_award", models.PositiveIntegerField(default=0)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="achievements.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-earned_at"],
                        name="achievement_user_id_d7ca0a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "badge"), name="unique_user_badge"
                    )
                ],
            },
        ),
    ]
