# Generated by Django 6.1.1 on 2026-09-18 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_messages',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('connections', 'Connections only'), ('nobody', 'Nobody')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentor_available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.JSONField(default=dict)),
                ('journaling', models.JSONField(default=dict)),
                ('social', models.JSONField(default=dict)),
                ('appearance', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
