# Generated by Django 5.2.17 on 2026-09-19 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="show_profile_views",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ProfileView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["profile_owner", "-last_seen_at"],
                        name="users_profi_profile_de7a93_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("viewer", "profile_owner", "viewed_on"),
                        name="unique_profile_view_per_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("viewer", models.F("profile_owner")), _negated=True
                        ),
                        name="no_self_profile_view",
                    ),
                ],
            },
        ),
    ]
