# Generated by Django 5.2.17 on 2026-09-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_journal_visibility_default_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tagline",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
