# Generated by Django 6.1.1 on 2026-09-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('calm', 'Calm'), ('excited', 'Excited'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('angry', 'Angry'), ('tired', 'Tired'), ('overwhelmed', 'Overwhelmed')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('intensity', models.PositiveSmallIntegerField(default=5)),
                ('description', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
