# Generated by Django 6.1.1 on 2026-09-18 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moodcheckin',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='moodcheckin',
            index=models.Index(fields=['owner', '-created_at'], name='moods_moodc_owner_i_45c543_idx'),
        ),
    ]
