# Generated by Django 6.1.1 on 2026-09-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodcheckin',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Angry', 'Angry'), ('Excited', 'Excited'), ('Anxious', 'Anxious'), ('Calm', 'Calm'), ('Frustrated', 'Frustrated'), ('Content', 'Content'), ('Lonely', 'Lonely'), ('Grateful', 'Grateful'), ('Stressed', 'Stressed'), ('Hopeful', 'Hopeful')], max_length=20),
        ),
    ]
